# Generated by Django 5.2 on 2025-04-19 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_productocomprado'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='productos',
            field=models.ManyToManyField(through='tienda.ProductoComprado', to='tienda.producto'),
        ),
        migrations.AlterField(
            model_name='productocomprado',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_comprado', to='tienda.compra'),
        ),
        migrations.DeleteModel(
            name='ItemCompra',
        ),
    ]
